tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#003434",
        "on-primary": "#ffffff",
        "primary-container": "#0f4c4c",
        "on-primary-container": "#85bbbb",
        "secondary": "#176969",
        "on-secondary": "#ffffff",
        "secondary-container": "#a4ecec",
        "on-secondary-container": "#1e6d6d",
        "tertiary": "#472600",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#663900",
        "on-tertiary-container": "#f99b2f",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "surface": "#f8f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#404848",
        "outline": "#707978",
        "outline-variant": "#bfc8c8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#306767",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#9ad0d0",
        "primary-fixed": "#b5edec",
        "primary-fixed-dim": "#9ad0d0",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#134f4f",
        "secondary-fixed": "#a7efef",
        "secondary-fixed-dim": "#8bd3d2",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f50",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb872",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max": "1200px",
        "base": "8px",
        "ad-slot-margin": "48px",
      },
      fontFamily: {
        "headline-lg": ["Sora"],
        "headline-md": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "display-num": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-num": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
}
